### ISSUE TITLE
Upgrade River Endpoint to use GlobusComputeEngine

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#545]
The Compute team has informed us that the HighThroughputEngine - which the River endpoint uses - has been marked for deprecation. They recommend we move to a config.yaml that looks like this ...

```
display_name: {{ coalesce .Values.endpointDisplayName .Values.endpointName .Release.Name }}
heartbeat_period: 15
heartbeat_threshold: 200
detach_endpoint: False

engine:
    type: GlobusComputeEngine
    label: kube
    encrypted: False
    max_workers_per_node: {{ .Values.maxWorkersPerPod }}
    worker_debug: {{- ternary "True" "False" .Values.workerDebug }}
    working_dir: {{ .Values.logDir }}

    address:
        type: address_by_route
    
    job_status_kwargs:
        max_idletime: {{ .Values.maxIdleTime }}

    provider:
        type: KubernetesProvider
        init_blocks: {{ .Values.initBlocks }}
        min_blocks: {{ .Values.minBlocks }}
        max_blocks: {{ .Values.maxBlocks }}
        init_cpu: {{ .Values.initCPU }}
        max_cpu: {{ .Values.maxCPU }}
        init_mem: {{ .Values.initMem }}
        max_mem: {{ .Values.maxMem }}
        image: {{ .Values.workerImage }}
        worker_init: {{ .Values.workerInit }}
        namespace: {{ .Values.workerNamespace }}
        pod_name: globus-compute-pod
        {{- if .Values.imagePullSecret }}
        secret: {{ .Values.imagePullSecret }}
        {{- end }}
```

# Acceptance Criteria
The River endpoint works and is no longer using the HighThroughputEngine
